backend:
  name: github
  repo: s-saanvi/portfolio
  branch: main # Branch to update

media_folder: "public/images/blog" # Media files will be stored in the repo under public/images/blog
public_folder: "/images/blog" # The src attribute for uploaded media will begin with /images/blog

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Cover Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
